worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: debug

is-testing: false

server-port: 8080
server-grpc-port: 8081

hello-endpoint: '[::1]:8081'

dbconnection: 'postgresql://pg_grpc_service_template_user:password@localhost:5432/pg_grpc_service_template_db_1'
